//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductLookUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantity
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int StoreID { get; set; }
        public int Quantity1 { get; set; }
    }
}
